openapi: 3.0.1
info:
  title: Swagger Petstore
  description: 'This is a sample server Petstore server.  You can find out more about     Swagger
    at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For
    this sample, you can use the api key `special-key` to test the authorization     filters.'
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080/
paths:
  /sendMoney:
    post:
      tags:
        - Financial Transaction
      summary: transfer money
      operationId: transfer money
      requestBody:
        description: Transfer money from senders bank account to receivers bank account
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FinancialTransaction'
        required: true
      responses:
        '201':
          description: Created.
        '400':
          description: Bad request.
        '406':
          description: Not Acceptable.
components:
  schemas:
    FinancialTransaction:
      type: object
      required:
        - sender
        - receiver
        - amount
        - nonce
      properties:
        sender:
          type: integer
          format: int
        receiver:
          type: integer
          format: int
        amount:
          $ref: '#/components/schemas/Amount'
        nonce:
          type: string
          format: UUID
    Amount:
      type: object
      required:
        - currency
        - value
      properties:
        currency:
          type: string
          enum:
            - "EUR"
            - "USD"
        value:
          type: integer
          format: int
